### ISSUE TITLE
StorageExpiryModule の medium が効かない

### ISSUE THREAD

**Issue by kalibora** [bearsunday/BEAR.QueryRepository#40]
すみません。ちょっと今忙しくて issue だけあげさせてもらいます。

下記の行を直すだけだと思っていますが、動作確認はしておりません。
https://github.com/bearsunday/BEAR.QueryRepository/blob/f7d2665b2181b4d41c891d86eeaf3dd1ae250a2b/src/StorageExpiryModule.php#L38

**Comment by koriym** [comment]
直ぐ直します！

**Comment by koriym** [comment]
[v1.4.4](https://github.com/bearsunday/BEAR.QueryRepository/releases/tag/1.4.4)でリリースしました

**Comment by kalibora** [comment]
ありがとうございます！

**Comment by koriym** [comment]
報告ありがとうございました。
Let's make things move forward !
