### ISSUE TITLE
`@Refresh` の処理時に Uncaught TypeError が発生する

### ISSUE THREAD

**Issue by amashigeseiji** [bearsunday/BEAR.QueryRepository#76]
エラー時の画面を添付します。
![image](https://user-images.githubusercontent.com/1837070/94436131-0a757b80-01d7-11eb-8264-c7e1955b1102.png)

# 詳細

以下のようなリソース定義があるとします。

```php
namespace Sample\Resource\Page;

use BEAR\RepositoryModule\Annotation\Cacheable;
use BEAR\RepositoryModule\Annotation\Refresh;

/**
 * @Cacheable
 */
class Sample extends ResourceObject
{
    public function onGet(int $id) : ResourceObject
    {
        return $this;
    }

    /**
     * @Refresh(uri="page://self/sample?id={id}")
     */
    public function onPut(int $id, string $name) : ResourceObject
    {
        return $this;
    }
}
```

`/sample?id=1&name=hgoe` に対する put 処理が実行された後、[BEAR\QueryRepository\CommandInterceptor](https://github.com/bearsunday/BEAR.QueryRepository/blob/1.x/src/CommandInterceptor.php) から [BEAR\QueryRepository\RefreshSameCommand::command()](https://github.com/bearsunday/BEAR.QueryRepository/blob/1.x/src/RefreshSameCommand.php#L28) が実行されると思います。

この `RefreshSameCommand` はキャッシュのパージ処理実行後に、ターゲットとなるリソースの onGet メソッドが定義されている場合に呼び出しています。

https://github.com/bearsunday/BEAR.QueryRepository/blob/1.6.8/src/RefreshSameCommand.php#L28-L48
```php
    public function command(MethodInvocation $invocation, ResourceObject $ro)
    {
        $method = $invocation->getMethod()->getName();
        if ($method === 'onGet' || $method === 'onPost') {
            return;
        }
        unset($invocation);
        $getQuery = $this->getQuery($ro);
        $delUri = clone $ro->uri;
        $delUri->query = $getQuery;


        // delete data in repository
        $this->repository->purge($delUri);


        // GET for re-generate (in interceptor)
        $ro->uri->query = $getQuery;
        $get = [$ro, 'onGet'];
        if (is_callable($get)) {
            \call_user_func_array($get, array_values($getQuery));
        }
    }
```

`$this->getQuery($ro)` も同クラス内ですが、こちらはリソースオブジェクトに刺さっているAbstractUriからクエリを作ります。それで、一般的にHTTPリクエストは string として処理されているため、この `getQuery($ro)` に入っている値も基本的には(事前に型変換が行われていない場合)すべて string なのではないかと思います。

それで、このまま `Sample::onGet(int $id)` を呼び出すと、 `RefreshSameCommand` クラスが `declare(strict_types=1);` になっているため、TypeError が発生するものと思います。

# 対応方針の検討

以下の２つの方針が考えられると思います。

1. `RefreshSameCommand` の `declare(strict_types=1)` を外す
2. `RefreshSameCommand::getQuery()` の処理中で、ReflectionParameter から読み取った型に合わせてパラメータをキャストする

個人的には、2 は不要な複雑性を呼び込むように見え、 1 のほうが妥当な修正ではないかと考えています。

**Comment by koriym** [comment]
@amashigeseiji 1の方法でfixして(BEAR.ResourceのInvokerも同様です）`1.6.9`としてリリースしました！

https://github.com/bearsunday/BEAR.QueryRepository/releases/tag/1.6.9

**Comment by amashigeseiji** [comment]
早速のご対応ありがとうございます！！！
